/**
 * Career-page directory for the MNCs most likely to hire SAP / supply-chain /
 * AI talent.
 *
 * Every URL here was actually fetched and checked before being committed — and
 * for search links, a differential test confirmed the keyword filter really
 * changes the results. Nothing here is a guessed URL. Researched 2026-07-22.
 *
 * Career sites move. If a link 404s, fix it here rather than in the UI.
 */

export type CareerSite = {
  name: string;
  /** Job SEARCH page (not the marketing "why work here" page). */
  careersUrl: string;
  /** Canonical ATS family, for grouping. */
  ats: string;
  /** Exactly what was observed, incl. any front end over the backend ATS. */
  atsDetail: string;
  accountRequired: boolean;
  /** Deep link pre-filtered to SAP roles, where one is constructible. */
  sapSearchUrl: string | null;
  applySteps: string;
  notes: string;
};

export const CAREER_SITES: CareerSite[] = [
  {
    name: "Accenture",
    careersUrl: "https://www.accenture.com/us-en/careers/jobsearch",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://www.accenture.com/us-en/careers/jobsearch?jk=SAP",
    applySteps: "Search on accenture.com, then 'Apply' hands off to Workday (accenture.wd103.myworkdayjobs.com/AccentureCareers). Workday candidate account (email + password) required. Resume upload is auto-parsed into work history/education, which you then edit. Standard Workday screening questions plus US voluntary EEO/veteran/disability. Some roles add an online assessment — HackerRank coding, ~30-90 min, external AI tools explicitly not permitted. Then phone/video/in-person interviews, then offer.",
    notes: "careersUrl 200 (bare curl). jk=SAP filters server-side: 0 'SAP' mentions unfiltered vs 54 filtered. Workday backend independently confirmed — POST to accenture.wd103.myworkdayjobs.com/wday/cxs/accenture/AccentureCareers/jobs with searchText 'SAP' returned tota",
  },
  {
    name: "Deloitte",
    careersUrl: "https://apply.deloitte.com/en_US/careers/SearchJobs",
    ats: "Avature",
    atsDetail: "Avature",
    accountRequired: true,
    sapSearchUrl: "https://apply.deloitte.com/en_US/careers/SearchJobs/SAP",
    applySteps: "Account required — register at apply.deloitte.com/en_US/careers/Register before applying. Resume upload with parsing into a candidate profile. Job-specific screening/eligibility questions (work authorization, sponsorship, independence/conflict-of-interest). Some roles include an online assessment battery (~45-60 min, 4 parts). Typically 2-3 interview rounds mixing behavioral, technical and case formats. Status tracked in the candidate profile.",
    notes: "careersUrl 200 (bare curl). Path-based keyword search confirmed filtering: 0 'SAP' mentions on the unfiltered page vs 36 on /SearchJobs/SAP, and page size dropped 130KB -> 127KB. ATS confirmed by fingerprint: 7 'avature' references in page source. Swap the las",
  },
  {
    name: "IBM",
    careersUrl: "https://www.ibm.com/careers/search",
    ats: "Avature",
    atsDetail: "Avature",
    accountRequired: true,
    sapSearchUrl: "https://www.ibm.com/careers/search?q=SAP",
    applySteps: "Search runs on ibm.com, but every job detail and the apply flow live on careers.ibm.com/en_US/careers/JobDetail?jobId= — an Avature portal. Candidate account required; you create an online profile, upload a resume, and track status under 'My profile' > 'Your applications'. You apply to one req at a time, but entered data carries over to the next application (editable each time). Screening questions cover work authorization and relocation. Typical flow: recruiter screen, then 1-2 technical/behavioral interviews; some roles add an IBM cognitive/behavioral assessment.",
    notes: "IN A REAL BROWSER. careersUrl 200. Raw curl of ?q=SAP is byte-identical to a control (client-side React render), so I loaded it in a browser: '1 – 30 of 147 items' with titles 'SAP Functional Consultant', 'SAP SD Specialist', 'SAP Fiori Developer', 'Package Sp",
  },
  {
    name: "Infosys",
    careersUrl: "https://digitalcareers.infosys.com/infosys/global-careers",
    ats: "Custom",
    atsDetail: "custom",
    accountRequired: true,
    sapSearchUrl: "https://digitalcareers.infosys.com/infosys/global-careers?keyword=SAP",
    applySteps: "Infosys-built 'Digital Careers' portal, no third-party ATS branding. The apply page offers two paths: 'I have an account → Login', or 'I'm applying for the first time → Apply', which creates a candidate profile. Resume upload, personal and work-authorization details, plus role-specific screening questions (US applications require visa-status disclosure). Then recruiter screen, technical round(s), and a managerial/HR round.",
    notes: "careersUrl 200. ?keyword=SAP filters server-side — three-way differential: unfiltered 321KB/104 SAP mentions, keyword=SAP 323KB/195, nonsense keyword 286KB/94. Sizes and counts all move, so the param is real. (The residual ~94 mentions on the control page come",
  },
  {
    name: "Tata Consultancy Services",
    careersUrl: "https://ibegin.tcsapps.com/candidate/",
    ats: "Custom",
    atsDetail: "custom",
    accountRequired: true,
    sapSearchUrl: null,
    applySteps: "You can browse and search openings without logging in, but applying requires registering an iBegin account ('New Users Register with us'). Registration builds a candidate profile: resume upload plus education, experience and skills. TCS then runs its own funnel — for experienced/lateral US hires this is typically recruiter screen, one or two technical interviews, a managerial round, then HR. Freshers and India campus hiring go through a different portal and require the TCS NQT aptitude test.",
    notes: "careersUrl 200, title 'TCS iBegin' — genuine portal. atsPlatform 'custom' confirmed: zero third-party ATS vendor strings in page source. HOST WARNING INDEPENDENTLY CONFIRMED — I re-tested the widely-cited alternatives and both fail outright: ibegin.tcs.com and",
  },
  {
    name: "Cognizant",
    careersUrl: "https://careers.cognizant.com/us-en/jobs/",
    ats: "Taleo",
    atsDetail: "Taleo",
    accountRequired: true,
    sapSearchUrl: "https://careers.cognizant.com/us-en/jobs/?keyword=SAP",
    applySteps: "careers.cognizant.com is only the search/marketing front end — every 'Apply now' button links out to Oracle Taleo (cognizant.taleo.net/careersection/.../jobapply.ftl, verified). A Taleo account is required; you can either pre-fill the application from an uploaded resume or complete it manually. Screening questions cover work authorization, sponsorship and location. Published stages: Application → short recruiter intro call → hiring-team interviews (some roles add technical assessments and/or client interviews) → decision. Education, employment, and possibly criminal/credit checks run post-offer.",
    notes: "Bot-blocked to scripts but valid. bare curl returns 403 on both URLs; with a browser User-Agent both return 200. Kept per the 403 rule (careers.cognizant.com is unambiguously Cognizant's official careers host). Filtering confirmed by three-way differential: un",
  },
  {
    name: "Capgemini",
    careersUrl: "https://www.capgemini.com/us-en/careers/join-capgemini/job-search/",
    ats: "SuccessFactors",
    atsDetail: "Capgemini-built front end over SAP SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://www.capgemini.com/us-en/careers/join-capgemini/job-search/?page=1&size=11&country_code=us-en&keyword=SAP",
    applySteps: "The search UI is a Capgemini-built front end; the candidate profile and apply backend is SAP SuccessFactors (career5.successfactors.eu, company=capgemitecP3 — host confirmed reachable, HTTP 200). Capgemini states the application takes 3-5 minutes: name, contact details, CV/resume mandatory, cover letter optional. That creates a 'candidate space' account for tracking status. Then a mix of behavioral, technical and cultural-fit interviews and assessments, by phone, video or in person. Offer leads into the 'GetONBOARD' pre-boarding program.",
    notes: "IN A REAL BROWSER. careersUrl 200. Raw curl could NOT prove filtering (SAP page 189,236 bytes vs nonsense control 189,306 bytes vs unfiltered 189,208 — all effectively identical, results are client-side rendered), so I loaded the deep link in a browser and con",
  },
  {
    name: "Wipro",
    careersUrl: "https://careers.wipro.com/search/",
    ats: "SuccessFactors",
    atsDetail: "SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://careers.wipro.com/search/?q=SAP",
    applySteps: "SAP SuccessFactors RMK site. Register a Wipro Careers account and upload a resume; you receive a candidate/employee ID used to track status and apply to further openings. SuccessFactors parses the resume into your profile, then screening questions. Stages: resume screening → online assessment (role-dependent) → technical interview → HR interview → background verification → offer.",
    notes: "careersUrl 200 (bare curl). ?q=SAP filters server-side — page title changes from 'Wipro Limited Jobs' to 'SAP - Wipro Limited Jobs' and SAP mentions go 14 -> 64. Server-rendered title change is strong proof. ATS confirmed by fingerprint: 9 'successfactors' ref",
  },
  {
    name: "SAP",
    careersUrl: "https://jobs.sap.com/search/",
    ats: "SuccessFactors",
    atsDetail: "SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://jobs.sap.com/search/?q=supply%20chain",
    applySteps: "Browse and search freely without signing in. Applying requires an SAP candidate account (email + password) created at first apply, or Social Apply via LinkedIn/XING to prefill. You then complete a Candidate Profile: resume upload with auto-parse into work experience/education fields, contact details, cover letter (optional), plus screening and EEO/voluntary-disclosure questions. Early-talent and graduate programs add an online assessment; experienced-hire SAP roles typically do not.",
    notes: "careersUrl 200 (bare curl). ?q= filters server-side — page title changes from 'SAP Jobs' to 'Supply Chain - SAP Jobs' and size grows 117KB -> 126KB. jobs.sap.com is SAP's own SuccessFactors Recruiting Marketing site, so the apply UX matches the SuccessFactors ",
  },
  {
    name: "Microsoft",
    careersUrl: "https://apply.careers.microsoft.com/careers",
    ats: "SuccessFactors",
    atsDetail: "Eightfold front end over SAP SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://apply.careers.microsoft.com/careers?query=SAP",
    applySteps: "Microsoft migrated to a new careers platform in Nov 2025; the old jobs.careers.microsoft.com search redirects here. Search and browse work logged out; submitting requires signing in to a candidate account. Resume upload with skill parsing, profile completion, role-specific screening questions, and voluntary disclosures. No general aptitude test for corporate/consulting roles; engineering roles get a technical screen rather than an ATS assessment. Application history from the pre-Nov-2025 portal did NOT carry over.",
    notes: "UPGRADED FROM UNCONFIRMED TO VERIFIED. careersUrl 200. Raw curl could not prove filtering (SAP 687,653 bytes vs control 689,201 vs unfiltered 687,633 — client-side render), so I loaded ?query=SAP in a real browser: '43 jobs' with 'Senior Azure SAP Specialist' ",
  },
  {
    name: "Oracle",
    careersUrl: "https://careers.oracle.com/en/sites/jobsearch/jobs",
    ats: "Oracle Recruiting",
    atsDetail: "Oracle Recruiting Cloud (Oracle Fusion HCM)",
    accountRequired: true,
    sapSearchUrl: "https://careers.oracle.com/en/sites/jobsearch/jobs?keyword=SAP",
    applySteps: "Candidate account required to submit (email verification), though you can start by uploading a resume to get AI-generated job recommendations. Flow: resume upload + parse, profile with experience/education, Oracle's generative-AI skill suggestions (review these — they feed the match score), role screening questions, EEO/voluntary disclosures. No standardized pre-hire assessment for functional/consulting roles.",
    notes: "IN A REAL BROWSER, WITH A CORRECTION. careersUrl 200. Raw curl is byte-identical filtered vs unfiltered (client-side render), so I loaded ?keyword=SAP in a browser: the param DOES filter, returning 'JOBS 32 / JOB SEARCH RESULTS 32'. IMPORTANT CORRECTION: none ",
  },
  {
    name: "Salesforce",
    careersUrl: "https://www.salesforce.com/company/careers/jobs/",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://salesforce.wd12.myworkdayjobs.com/en-US/External_Career_Site?q=supply%20chain",
    applySteps: "Search happens on the Salesforce-branded front end; clicking Apply hands off to Workday, where you create a Workday candidate account (email + password) scoped to Salesforce. Standard Workday flow: 'Autofill with Resume' parse, then correct the parsed work history/education (the parser is lossy — always verify), contact info, screening questions, self-identification and voluntary disclosures. Salesforce explicitly recommends applying to a MAXIMUM of 3 roles per 12 months, so target carefully.",
    notes: "careersUrl 200 (bare curl, resolves to .../jobs/?bc=HL). Legacy careers.salesforce.com/en/jobs/ confirmed 200 and redirects here. Workday backend independently re-confirmed via the CXS API — POST to salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/Externa",
  },
  {
    name: "ServiceNow",
    careersUrl: "https://careers.servicenow.com/jobs/",
    ats: "SmartRecruiters",
    atsDetail: "SmartRecruiters",
    accountRequired: false,
    sapSearchUrl: "https://careers.smartrecruiters.com/ServiceNow?search=supply%20chain",
    applySteps: "SmartRecruiters-backed apply, the lightest on this list: no mandatory password-protected account to submit — you can apply with resume upload (auto-parsed) or LinkedIn import plus contact details, a short set of screening questions, and EEO. Creating an account is optional and only used to track status. Contract/contingent roles are routed through Magnit, not this site.",
    notes: "Bot-blocked to scripts but valid. careersUrl returns 403 to bare curl, 200 with a browser User-Agent (title 'Explore Jobs | ServiceNow Careers'). Kept per the 403 rule. httpStatus CORRECTED: the prior entry recorded 403 for the sapSearchUrl, but careers.smartr",
  },
  {
    name: "Workday",
    careersUrl: "https://workday.wd5.myworkdayjobs.com/en-US/Workday",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://workday.wd5.myworkdayjobs.com/en-US/Workday?q=supply%20chain",
    applySteps: "Workday candidate account required (email + password, tenant-specific — a Workday account at another employer does not carry over). 'Autofill with Resume' parses the file into work history and education; review carefully. Then contact info, application questions, self-identification, voluntary disclosures, and an optional 'Introduce Yourself' talent-community submission if no req fits.",
    notes: "Both URLs 200 (bare curl returns the ~8KB Workday SPA shell, which is expected and not a failure). Backend independently confirmed via the CXS API: POST /wday/cxs/workday/Workday/jobs with searchText 'supply chain' returns total 3 — EXACTLY matching the prior ",
  },
  {
    name: "Amazon",
    careersUrl: "https://www.amazon.jobs/en/search",
    ats: "Custom",
    atsDetail: "custom",
    accountRequired: true,
    sapSearchUrl: "https://www.amazon.jobs/en/search?base_query=SAP",
    applySteps: "amazon.jobs account required, and it is SEPARATE from an Amazon retail/Prime account. Resume upload with parse, profile, work-authorization and basic screening questions. Many corporate and tech roles add an online assessment sent after submission — typically a work-simulation exercise plus a work-style survey (Leadership Principles based); SDE roles get a coding OA. Operations/fulfillment roles add a virtual job preview. Status tracked in the amazon.jobs dashboard.",
    notes: "SERVER-SIDE. Both URLs 200. The HTML page is an SPA (SAP 37,758 bytes vs control 37,778 — no useful differential), but the underlying JSON endpoint confirms the param: https://www.amazon.jobs/en/search.json?base_query=SAP returns hits: 543, EXACTLY matching th",
  },
  {
    name: "Google",
    careersUrl: "https://www.google.com/about/careers/applications/jobs/results/",
    ats: "Custom",
    atsDetail: "custom (in-house gHire)",
    accountRequired: true,
    sapSearchUrl: "https://www.google.com/about/careers/applications/jobs/results/?q=supply%20chain",
    applySteps: "Google account sign-in plus a Careers Profile is required — the profile is the central record and you cannot apply without it. Resume upload (PDF preferred); transcripts optional and mostly for early-career. HARD CAP: only 3 applications per rolling 30-day window, and employee referrals count against that 3. You must wait 90 days before re-applying to the same job. You can save drafts and edit before submitting, but nothing can be changed after submission. No ATS-stage aptitude test; screening is recruiter-led.",
    notes: "SERVER-SIDE. Both URLs 200 (bare curl). Filtering proven by differential: ?q=supply%20chain returns 1,250,072 bytes containing 190 'supply chain' occurrences, while a nonsense keyword returns 995,809 bytes — a ~254KB drop, so results are genuinely server-rende",
  },
  {
    name: "The Coca-Cola Company",
    careersUrl: "https://coke.wd1.myworkdayjobs.com/coca-cola-careers",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://coke.wd1.myworkdayjobs.com/coca-cola-careers?q=SAP",
    applySteps: "Workday account required (email + password, separate from any other Workday tenant). Resume upload with autofill-from-resume parsing that pre-populates work history and education for review/correction. Application questions cover work authorization and visa sponsorship, plus voluntary EEO/veteran/disability disclosures. No pre-hire assessment at the apply stage. Progress saves, so a partial application can be resumed.",
    notes: "Both URLs 200 (bare curl returns the ~7KB Workday SPA shell — expected). Backend independently confirmed via the CXS API: POST /wday/cxs/coke/coca-cola-careers/jobs with searchText 'SAP' returns total 32, EXACTLY matching the prior claim, top hits 'Senior Mana",
  },
  {
    name: "PepsiCo",
    careersUrl: "https://www.pepsicojobs.com/main/jobs",
    ats: "iCIMS",
    atsDetail: "iCIMS",
    accountRequired: true,
    sapSearchUrl: "https://uscareers-pepsico.icims.com/jobs/search?searchKeyword=SAP",
    applySteps: "iCIMS candidate profile required (account with email + password). Resume upload with parsing into profile fields. Screening/knockout questions on work authorization and sponsorship are standard. PepsiCo adds assessments for a subset of roles (situational-judgement / virtual job tryout style), surfaced after the initial submission rather than inline. The pepsicojobs.com front-end is JavaScript-rendered, so the search box needs a real browser; the iCIMS URL below works directly.",
    notes: "BY DIFFERENTIAL. Both URLs 200 (bare curl). searchKeyword=SAP returns 158,565 bytes of real listings — extracted titles include '459154 - Sr. Analyst, SAP Order To Cash', '465411 - Regional Category Procurement Coordinator', '456444 - Blue Yonder WMS DSO Direc",
  },
  {
    name: "Nestle",
    careersUrl: "https://www.nestlejobs.com/job-search",
    ats: "SuccessFactors",
    atsDetail: "SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://www.nestlejobs.com/job-search?keyword=SAP",
    applySteps: "Account required on the SAP SuccessFactors candidate portal (career2.successfactors.eu). Resume upload with parsing into a candidate profile that persists across applications. Standard screening questions on work authorization, relocation and sponsorship. An Avature talent-CRM layer (nestleus.avature.net) sits alongside it for talent-community signup and event registration, so you may end up with two separate logins.",
    notes: "BY DIFFERENTIAL. Both URLs 200 (bare curl). ?keyword= is confirmed as the correct param by a three-way test: unfiltered 59,832 bytes / 0 SAP mentions, keyword=SAP 60,142 bytes / 3 SAP mentions, nonsense keyword 42,495 bytes / 0 — the ~18KB collapse on the cont",
  },
  {
    name: "Procter & Gamble",
    careersUrl: "https://www.pgcareers.com/global/en/search-results",
    ats: "Workday",
    atsDetail: "Phenom front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://www.pgcareers.com/global/en/search-results?keywords=SAP",
    applySteps: "Two-layer stack: you browse on the Phenom-powered pgcareers.com site, but the Apply button hands off to Workday at pg.wd5.myworkdayjobs.com/1000, where a Workday account is required. Resume upload with autofill parsing. P&G is the most assessment-heavy company on this list — its published hiring process includes an online assessment stage (reasoning/behavioral) before interviews, and candidates should expect it as a gate rather than an optional extra. Budget real time for this application.",
    notes: "TWO WAYS. Both URLs 200 (bare curl). Server-side filtering confirmed by differential: unfiltered 169,252 bytes / 7 SAP mentions vs keywords=SAP 164,214 bytes / 27 SAP mentions. Workday backend independently confirmed via the CXS API: POST /wday/cxs/pg/1000/job",
  },
  {
    name: "Unilever",
    careersUrl: "https://careers.unilever.com/en/search-jobs",
    ats: "Workday",
    atsDetail: "Radancy front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://careers.unilever.com/en/search-jobs/SAP",
    applySteps: "Radancy/TalentBrew-powered search layer on careers.unilever.com, with apply handing off to Workday (unilever.wd3.myworkdayjobs.com) where an account is required. Resume upload with parsing. Screening questions on work authorization and sponsorship. Unilever has a well-documented history of gamified/behavioral assessment and asynchronous video interviews, heaviest in early-careers tracks — experienced-hire supply-chain roles are typically lighter, but expect at least a digital screening step.",
    notes: ", PATH-FORM GOTCHA CONFIRMED. Both URLs 200 (bare curl). The path form genuinely filters: unfiltered /en/search-jobs is 998,096 bytes with 1 SAP mention, /en/search-jobs/SAP is 586,938 bytes with 24 SAP mentions — a ~411KB drop. Use the path form, NOT ?search=",
  },
  {
    name: "Mondelez International",
    careersUrl: "https://mdlz.wd3.myworkdayjobs.com/External",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://mdlz.wd3.myworkdayjobs.com/External?q=SAP",
    applySteps: "Workday account required. Resume upload with autofill parsing into work history and education. Application questions cover work authorization, sponsorship and relocation, plus voluntary EEO disclosures. No assessment at the apply stage. Talent Community signup is offered separately if nothing currently fits.",
    notes: "Both URLs 200 (bare curl returns the ~7.6KB Workday SPA shell — expected). Backend independently confirmed via the CXS API: POST /wday/cxs/mdlz/External/jobs with searchText 'SAP' returns total 728 (prior claim said 727 — within noise, effectively confirmed), ",
  },
  {
    name: "Colgate-Palmolive",
    careersUrl: "https://jobs.colgate.com/search/",
    ats: "SuccessFactors",
    atsDetail: "SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://jobs.colgate.com/search/?q=SAP",
    applySteps: "SAP SuccessFactors candidate account required (backend at career4.successfactors.com). Resume upload with parsing into a persistent candidate profile reusable across applications. Standard screening questions on work authorization and sponsorship. No assessment stage evident at apply time.",
    notes: "UPGRADED FROM 'CORRECT-BY-CONSTRUCTION' TO OUTPUT-VERIFIED. Both URLs 200 (bare curl). The prior entry flagged this deep link as unverifiable; I proved it server-side. Three-way differential: unfiltered page title 'Colgate-Palmolive Company Jobs' with 0 SAP me",
  },
  {
    name: "Kimberly-Clark",
    careersUrl: "https://kimberlyclark.wd1.myworkdayjobs.com/GLOBAL",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://kimberlyclark.wd1.myworkdayjobs.com/GLOBAL?q=SAP",
    applySteps: "Workday account required. Resume upload with autofill parsing. Application questions cover work authorization, sponsorship and voluntary EEO/veteran/disability disclosures. No assessment at the apply stage. Applications save mid-progress and can be resumed.",
    notes: "Both URLs 200 (bare curl returns the ~7.4KB Workday SPA shell — expected). Backend independently confirmed via the CXS API: POST /wday/cxs/kimberlyclark/GLOBAL/jobs with searchText 'SAP' returns total 58, EXACTLY matching the prior claim, with 'Master Data Ana",
  },
  {
    name: "Johnson & Johnson",
    careersUrl: "https://www.careers.jnj.com/en/jobs/",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://jj.wd5.myworkdayjobs.com/en-US/JJ?q=SAP",
    applySteps: "Browse freely on the branded careers.jnj.com front-end, but Apply hands off to the Workday tenant jj.wd5.myworkdayjobs.com/JJ. Workday account (email + password) required. Resume upload auto-parses into work history/education screens that you must review and correct. Standard screening questions: work authorization, sponsorship need, prior J&J employment, notice period. Voluntary EEO/veteran/disability disclosures. No coding test for functional/supply-chain roles. Drafts save; status visible under Candidate Home > My Applications.",
    notes: "Bot-blocked to scripts but valid. careersUrl returns 403 to bare curl, 200 with a browser User-Agent (title 'Explore current job openings | Johnson & Johnson Careers', 346KB). Kept per the 403 rule; careers.jnj.com is unambiguously J&J's official careers host.",
  },
  {
    name: "Pfizer",
    careersUrl: "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://pfizer.wd1.myworkdayjobs.com/en-US/PfizerCareers?q=SAP",
    applySteps: "Pure Workday — no separate marketing front-end, the job search page IS the ATS. Account required. Resume upload with auto-parse, editable experience/education steps, screening questions (work authorization, sponsorship, relocation), voluntary self-identification. Straightforward apply, typically 10-15 minutes once the profile exists.",
    notes: "— AND THE NEGATIVE FINDING IS CONFIRMED. Both URLs 200 (bare curl returns the ~6.9KB Workday SPA shell — expected). CXS API: POST /wday/cxs/pfizer/PfizerCareers/jobs with searchText 'SAP' returns total 17, EXACTLY matching the prior claim, and I confirmed the ",
  },
  {
    name: "Siemens",
    careersUrl: "https://jobs.siemens.com/en_US/externaljobs/SearchJobs",
    ats: "Avature",
    atsDetail: "Avature",
    accountRequired: true,
    sapSearchUrl: "https://jobs.siemens.com/en_US/externaljobs/SearchJobs?search=SAP",
    applySteps: "Siemens 'Careers Marketplace' runs on Avature. Registration required to apply; Avature builds a persistent candidate profile. Resume upload + parse, then a profile/questionnaire wizard. Some graduate and program roles add a video interview or online assessment; experienced professional hires generally do not. Site also offers an 'AI Recommendations' resume-match feature.",
    notes: "Both URLs 200 (bare curl). ?search=SAP filters server-side: 162,342 bytes / 25 SAP mentions unfiltered vs 171,145 bytes / 105 SAP mentions filtered. PARAM GOTCHA STANDS: it is ?search= — ?keyword= and ?keywords= silently return the unfiltered list, an easy tra",
  },
  {
    name: "3M",
    careersUrl: "https://3m.wd1.myworkdayjobs.com/Search",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://3m.wd1.myworkdayjobs.com/en-US/Search?q=SAP",
    applySteps: "Workday tenant, reached directly or via the vanity redirect 3m.com/apply. Account required. Resume upload with parse, experience/education review, screening questions and voluntary disclosures. 3M publishes an 'Application to Interview' candidate guide describing the funnel: application review, recruiter screen, hiring-manager interview, then panel/onsite.",
    notes: "Both URLs 200 (bare curl returns the ~6.6KB Workday SPA shell — expected). Backend independently confirmed via the CXS API: POST /wday/cxs/3m/Search/jobs with searchText 'SAP' returns total 82, EXACTLY matching the prior claim, with genuinely SAP-titled top hi",
  },
  {
    name: "Honeywell",
    careersUrl: "https://careers.honeywell.com/en/sites/Honeywell/jobs",
    ats: "Oracle Recruiting",
    atsDetail: "Oracle Recruiting Cloud (Oracle Fusion HCM)",
    accountRequired: true,
    sapSearchUrl: "https://careers.honeywell.com/en/sites/Honeywell/jobs?keyword=SAP",
    applySteps: "Oracle Recruiting Cloud on tenant ibqbjb.fa.ocs.oraclecloud.com (siteNumber CX_1); careers.honeywell.com is the vanity domain over it. Search and browse without an account. Applying requires an account, or sign-in via LinkedIn/Indeed which pre-fills the profile. Resume upload parses into the profile; the site also offers drag-and-drop resume upload that returns skill-matched job recommendations before you commit to applying. Screening questions on work authorization/sponsorship, plus voluntary disclosures.",
    notes: "BEST FIT — INDEPENDENTLY CONFIRMED IN A REAL BROWSER. Both URLs 200 (bare curl), but the raw HTML is byte-identical filtered vs unfiltered (Oracle ORC client-side render), so I loaded the deep link in a browser and read the rendered results. ?keyword=SAP retur",
  },
  {
    name: "GE Aerospace",
    careersUrl: "https://careers.geaerospace.com/global/en/search-results",
    ats: "Workday",
    atsDetail: "Phenom front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://careers.geaerospace.com/global/en/search-results?keywords=SAP",
    applySteps: "careers.geaerospace.com is a Phenom People careers experience layer (search, job alerts, talent community) sitting on the Workday tenant geaerospace.wd5.myworkdayjobs.com/GE_ExternalSite. Browse and search without an account; Apply redirects into Workday where an account is required. Resume upload + parse, experience/education review, screening questions covering work authorization, sponsorship, and — relevant to aerospace — US person / export-control (ITAR) status for defense-adjacent roles. Voluntary disclosures.",
    notes: "TWO WAYS. Both URLs 200 (bare curl). Phenom layer filtering confirmed by differential: 104,558 bytes / 6 SAP mentions unfiltered vs 101,438 bytes / 30 SAP mentions with ?keywords=SAP. Workday backend independently confirmed via the CXS API: POST /wday/cxs/geae",
  },
  {
    name: "Cargill",
    careersUrl: "https://careers.cargill.com/en/search-jobs",
    ats: "SuccessFactors",
    atsDetail: "Radancy front end + SuccessFactors ATS + Paradox conversational apply",
    accountRequired: true,
    sapSearchUrl: "https://careers.cargill.com/en/search-jobs/SAP",
    applySteps: "Three-layer stack, all three layers independently fingerprint-confirmed: Radancy/TalentBrew powers the careers site, SAP SuccessFactors is the actual ATS (career2.successfactors.eu, company=cargill), and Paradox 'Olivia' provides a conversational apply. Each posting exposes BOTH paths: the primary Apply Now button opens the Paradox chat/text flow, and a secondary link creates a SuccessFactors login. Corporate/salaried roles are best done through the SuccessFactors login for full resume upload and document control; the chat flow targets high-volume production roles.",
    notes: "STRONG FIT — RE-VERIFIED. Both URLs 200 (bare curl). Path-form filtering proven by differential: unfiltered /en/search-jobs is 937,751 bytes with 1 SAP mention, /en/search-jobs/SAP is 291,099 bytes with 34 SAP mentions — a ~647KB collapse. Keyword goes in the ",
  },
  {
    name: "Merck",
    careersUrl: "https://jobs.merck.com/us/en/search-results",
    ats: "Workday",
    atsDetail: "Phenom front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://msd.wd5.myworkdayjobs.com/en-US/SearchJobs?q=SAP",
    applySteps: "jobs.merck.com is a Phenom People experience layer over the Workday tenant msd.wd5.myworkdayjobs.com/SearchJobs. Applicant sign-in and Apply both route to Workday, where an account is required. Resume upload with parse, experience/education review, screening questions (work authorization, sponsorship, prior Merck/MSD employment), voluntary disclosures. Current employees use a separate internal Workday Jobs Hub.",
    notes: "careersUrl 200 (bare curl, title 'Your job search results | Merck Careers', 273KB). sapSearchUrl 200. Workday backend independently confirmed via the CXS API: POST /wday/cxs/msd/SearchJobs/jobs with searchText 'SAP' returns total 108, EXACTLY matching the prio",
  },
  {
    name: "EY (Ernst & Young)",
    careersUrl: "https://careers.ey.com/ey/search/",
    ats: "SuccessFactors",
    atsDetail: "SuccessFactors",
    accountRequired: true,
    sapSearchUrl: "https://careers.ey.com/ey/search/?q=SAP",
    applySteps: "Account required — create an EY careers profile (email + password) on the SuccessFactors career site. Resume upload with auto-parse to prefill the profile; option to import from LinkedIn. Application form covers work authorization, relocation, referral source, plus EEO/voluntary disclosure. Screening questions are role-specific. Experienced-hire consulting roles typically go straight to recruiter screen; campus/graduate tracks add game-based and situational assessments (EY Launch). Expect to also be pushed into an EY talent community.",
    notes: "Both URLs 200 (bare curl). ?q=SAP filters server-side — the page <title> changes from 'EY Jobs' to 'SAP - EY Jobs' and SAP mentions jump 13 -> 129 with size growing 196KB -> 204KB. A server-rendered title change is conclusive. ATS confirmed by fingerprint: 15 ",
  },
  {
    name: "PwC",
    careersUrl: "https://jobs-us.pwc.com/us/en/search-results",
    ats: "Workday",
    atsDetail: "Phenom front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://jobs-us.pwc.com/us/en/search-results?keywords=SAP",
    applySteps: "Browsing and search need no account, but clicking Apply hands off to PwC's Workday tenant (pwc.wd3.myworkdayjobs.com) where a candidate account is mandatory. Resume upload + parse prefills work history and education; LinkedIn/Indeed quick-apply available. Screening questions cover work authorization / visa sponsorship, mobility and travel willingness, and CPA or certification status. EEO and voluntary self-ID at the end. No upfront online assessment for experienced hires; campus applicants get PwC's virtual/game-based assessment. Workday saves a draft so you can resume a partial application.",
    notes: "Both URLs 200 (bare curl). Strongest server-side differential on this list: unfiltered 112,086 bytes / 5 SAP mentions vs ?keywords=SAP 143,024 bytes / 169 SAP mentions — a 31KB growth and 34x increase in SAP references, all server-rendered. ATS stack confirmed",
  },
  {
    name: "KPMG",
    careersUrl: "https://www.kpmguscareers.com/job-search/",
    ats: "Avature",
    atsDetail: "Avature (uskpmgats.avature.net), with kpmguscareers.com as the WordPress search front end",
    accountRequired: true,
    sapSearchUrl: "https://www.kpmguscareers.com/job-search/?keyword=SAP",
    applySteps: "Search and browse without an account; applying requires a KPMG candidate account on the Avature ATS (us-talentcommunity.kpmg.com / uskpmgats.avature.net). Resume upload with parsing, then manual correction of parsed fields is usually needed. Screening questions cover work authorization and sponsorship, prior KPMG employment, relocation, and independence/conflict-of-interest disclosures (KPMG asks about family financial holdings for audit-adjacent roles). EEO and self-ID at the end. Experienced hires: no assessment, straight to recruiter screen. Campus: online assessment plus a recorded video interview.",
    notes: "Both URLs 200 (bare curl). ?keyword=SAP filters server-side: 3 SAP mentions unfiltered vs 26 filtered, with a byte-size shift. AVATURE INDEPENDENTLY CONFIRMED TWO WAYS — us-talentcommunity.kpmg.com exposes avature.portal.id / avature.portal.name / avature.port",
  },
  {
    name: "Dell Technologies",
    careersUrl: "https://jobs.dell.com/en/sites/careers/jobs",
    ats: "Oracle Recruiting",
    atsDetail: "Oracle Recruiting Cloud (Oracle HCM Fusion) — jobs.dell.com proxies iawmqy.fa.ocs.oraclecloud.com",
    accountRequired: true,
    sapSearchUrl: "https://jobs.dell.com/en/sites/careers/jobs?keyword=SAP",
    applySteps: "Account required — an Oracle candidate profile (email verification via a one-time code). Resume upload + parse, or apply with LinkedIn/Indeed. Multi-step wizard: profile > experience > education > screening questions > diversity/EEO > review. Screening questions cover work authorization, sponsorship need, prior Dell employment, and location/hybrid onsite commitment (Dell enforces a return-to-office policy that appears as a hard screening question). No coding test or assessment for functional/SAP roles. Draft applications save to your candidate profile.",
    notes: "MATERIAL CORRECTION — the URL is valid but the prior entry oversold the opportunity. careersUrl 200; bare jobs.dell.com confirmed 302-redirecting to iawmqy.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/careers, confirming Oracle Recruiting Cloud. R",
  },
  {
    name: "HP",
    careersUrl: "https://apply.hp.com/careers",
    ats: "Workday",
    atsDetail: "Eightfold front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://apply.hp.com/careers?query=SAP",
    applySteps: "Two-stage. Eightfold lets you upload a resume for AI job-matching and see personalized role recommendations WITHOUT an account — genuinely useful for a career-pivot candidate since it scores your resume against reqs. Actually applying redirects into HP's Workday tenant, where an account is required. Workday flow: resume upload + parse, work history, screening questions (work authorization, sponsorship, prior HP/HPE employment, location), then EEO and voluntary self-ID. No assessment for experienced functional roles. Note jobs.hp.com is a WordPress marketing site, not the search tool.",
    notes: "IN A REAL BROWSER. Both URLs 200 (bare curl), but raw HTML gave no usable differential (Eightfold client-side render), so I loaded ?query=SAP in a browser: '85 jobs' with directly relevant titles — 'Senior Supply Planner - SAP IBP', 'SAP-IBP Configurator & Dev",
  },
  {
    name: "Intel",
    careersUrl: "https://intel.wd1.myworkdayjobs.com/External",
    ats: "Workday",
    atsDetail: "Workday",
    accountRequired: true,
    sapSearchUrl: "https://intel.wd1.myworkdayjobs.com/External?q=SAP",
    applySteps: "Account required — a Workday candidate account on Intel's tenant. Resume upload + parse, or autofill from a previous application. Screening questions cover work authorization and sponsorship, export-control / citizenship status (Intel asks this because of ITAR and government-program work), prior Intel employment, and site/relocation preference. EEO and self-ID at the end. No online assessment for business-systems or supply-chain roles; technical roles may add a take-home. Workday lets you track application status and withdraw from your candidate home page.",
    notes: "BEST IMMEDIATE FIT — RE-VERIFIED. Both URLs 200 (bare curl returns the ~6.8KB Workday SPA shell — expected). jobs.intel.com confirmed 302-redirecting straight to intel.wd1.myworkdayjobs.com/External, confirming pure Workday with no marketing front end. Backend",
  },
  {
    name: "Cisco",
    careersUrl: "https://careers.cisco.com/global/en/search-results",
    ats: "Workday",
    atsDetail: "Phenom front end over Workday",
    accountRequired: true,
    sapSearchUrl: "https://careers.cisco.com/global/en/search-results?keywords=SAP",
    applySteps: "Search freely without an account; Apply hands off to Cisco's Workday tenant (cisco.wd5.myworkdayjobs.com), which requires an account. Resume upload + parse; Cisco also supports building a profile that persists across applications. Screening questions cover work authorization and sponsorship, prior Cisco/Splunk employment, hybrid work location, and referral source. EEO and self-ID at the end. No assessment for business/supply-chain roles. Application status is trackable in Workday.",
    notes: "Both URLs 200 (bare curl). ?keywords=SAP filters server-side, proven conclusively by the <title> changing from ' Job Openings - Cisco Careers' to 'SAP Job Openings - Cisco Careers', with size dropping 151,221 -> 71,519 bytes and SAP mentions rising 5 -> 16. Th",
  },
  {
    name: "Schneider Electric",
    careersUrl: "https://careers.se.com/jobs",
    ats: "iCIMS",
    atsDetail: "iCIMS (Jibe career-site front end, careers-se.icims.com backend)",
    accountRequired: true,
    sapSearchUrl: "https://careers.se.com/jobs?keywords=SAP",
    applySteps: "An iCIMS candidate account is required to submit. Resume upload + parse is standard, but the site explicitly exposes 'Apply Without Resume', 'Apply With Cover Letter' and 'Apply Without Cover Letter' paths — unusually flexible. Screening questions cover work authorization and sponsorship, language proficiency, mobility/relocation, and prior Schneider employment. EEO and self-ID at the end. No assessment for experienced functional roles; graduate programs add one. Employee referrals are handled in-platform.",
    notes: "UPGRADED FROM 'CORRECT-BY-CONSTRUCTION' TO FULLY VERIFIED. Both URLs 200 (bare curl). Raw HTML gave no differential (SAP 801,277 bytes vs control 801,317 vs unfiltered 801,208 — client-side render), so I loaded ?keywords=SAP in a real browser and read the rend",
  },
];

/** Distinct ATS families present, most common first. */
export function atsFamilies(): Array<{ ats: string; count: number }> {
  const m = new Map<string, number>();
  for (const c of CAREER_SITES) m.set(c.ats, (m.get(c.ats) ?? 0) + 1);
  return [...m.entries()]
    .map(([ats, count]) => ({ ats, count }))
    .sort((a, b) => b.count - a.count);
}
