import type { Job, Project } from "./content-types";

/**
 * Used when Supabase is unconfigured or returns no rows so the public site
 * keeps rendering. Mirrors what was previously hardcoded in the components.
 */
export const FALLBACK_JOBS: Job[] = [
  {
    id: "seed-job-1",
    title: "SAP Business Analyst",
    category: "Enterprise & Integration",
    company: "The Coca-Cola Company",
    location: "Atlanta, USA",
    period: "Feb 2025 – Present",
    logo_src: "/logos/coca-cola.png",
    logo_bg: "#ffffff",
    description:
      "Supporting end-to-end supply chain operations across SAP S/4HANA and SAP Ariba, ensuring system stability and business continuity for global operations.",
    highlights: [
      "SAP S/4HANA & SAP Ariba integration",
      "ASN, inventory & delivery error resolution",
      "CIG and cXML root cause analysis",
      "UAT, regression testing & go-live support",
      "Liaison between business, IT & SAP CoE",
    ],
    tags: ["SAP S/4HANA", "SAP Ariba", "CIG", "cXML", "ASN"],
    notes: null,
    sort_order: 10,
  },
  {
    id: "seed-job-2",
    title: "SAP S/4HANA MM / SD Consultant",
    category: "Pharma & Compliance",
    company: "Xiromed",
    location: "New Jersey, USA",
    period: "Nov 2023 – Jan 2025",
    logo_src: null,
    logo_bg: "#0a4da2",
    description:
      "Managed SAP S/4HANA master data with 99.9% accuracy and delivered end-to-end MM, IM, and SD implementations for pharmaceutical operations.",
    highlights: [
      "99.9% master data accuracy",
      "End-to-end SAP MM, IM, SD delivery",
      "DSCSA compliance via TraceLink",
      "Global supply chain: APAC, EU, NA, LATAM",
      "Demand planning & forecasting support",
    ],
    tags: ["SAP MM/SD", "TraceLink", "DSCSA", "Supply Chain"],
    notes: null,
    sort_order: 20,
  },
  {
    id: "seed-job-3",
    title: "SAP S/4HANA Master Data Analyst",
    category: "Data Governance & Finance",
    company: "PepsiCo Inc.",
    location: "New York, USA",
    period: "Apr 2023 – Sept 2023",
    logo_src: "/logos/pepsico.png",
    logo_bg: "#004b93",
    description:
      "Reduced master-data-related errors by ~40% through root-cause analysis and standardized data maintenance across procurement and finance.",
    highlights: [
      "~40% error reduction via root-cause analysis",
      "Vendor & material master with SOX compliance",
      "Power BI reporting for data quality",
      "S/4HANA deployment & post-go-live support",
    ],
    tags: ["Master Data", "SOX", "Power BI", "S/4HANA"],
    notes: null,
    sort_order: 30,
  },
  {
    id: "seed-job-4",
    title: "Data Analyst",
    category: "Analytics & Procurement",
    company: "DenKen",
    location: "California, USA",
    period: "Dec 2022 – Mar 2023",
    logo_src: "/logos/denken.webp",
    logo_bg: "#2d2d2d",
    description:
      "Utilized MySQL and Tableau for data analysis, providing actionable insights for supplier optimization and cost reduction.",
    highlights: [
      "MySQL & Tableau data analysis",
      "Supplier negotiation & cost savings",
      "Sales & inventory trend optimization",
      "Cross-functional process improvements",
    ],
    tags: ["MySQL", "Tableau", "Data Analysis", "Procurement"],
    notes: null,
    sort_order: 40,
  },
  {
    id: "seed-job-5",
    title: "SAP SRM / Vendor Master Data Analyst",
    category: "Master Data Management",
    company: "IFF",
    location: "Hyderabad, India",
    period: "May 2020 – Feb 2021",
    logo_src: "/logos/iff.webp",
    logo_bg: "#1a1a1a",
    description:
      "Created and maintained vendor master records in SAP SRM/S/4HANA, performing validation and cleansing to reduce data inconsistencies.",
    highlights: [
      "Vendor master in SAP SRM/S/4HANA",
      "Data validation & cleansing",
      "Procurement leadership reporting",
      "SOP documentation & knowledge transfer",
    ],
    tags: ["SAP SRM", "Vendor Master", "Procurement"],
    notes: null,
    sort_order: 50,
  },
  {
    id: "seed-job-6",
    title: "IT Procurement Associate",
    category: "Procurement & Sourcing",
    company: "SAAS IT",
    location: "Chennai, India",
    period: "Mar 2019 – Apr 2020",
    logo_src: "/logos/saasit.png",
    logo_bg: "#1a1a1a",
    description:
      "Managed procurement using SAP S/4HANA and SAP Ariba, achieving ~10% cost savings through data-driven vendor negotiations.",
    highlights: [
      "SAP S/4HANA & Ariba procurement",
      "~10% cost savings via negotiations",
      "RFI/RFQ analysis & recommendations",
      "Cross-training & knowledge sharing",
    ],
    tags: ["SAP Ariba", "Procurement", "RFQ/RFI"],
    notes: null,
    sort_order: 60,
  },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "seed-proj-1",
    title: "WealthClaude",
    subtitle: "AI Finance Tracking Platform",
    number: "01",
    description:
      "Full portfolio tracker with 3D globe across 51 markets, AI market intelligence, dividend analytics, 15+ calculators, and 7-layer security.",
    link: "https://www.wealthclaude.com",
    tags: ["Next.js", "Supabase", "Three.js", "Stripe", "Groq AI"],
    gradient: "from-[#22c55e] to-[#16a34a]",
    preview: "/previews/wealthclaude.png",
    sort_order: 10,
  },
  {
    id: "seed-proj-asg",
    title: "Air Surface Global",
    subtitle: "AI Logistics & Marketing Platform",
    number: "02",
    description:
      "Intelligent freight logistics platform with AI route planning across air, ocean, road, and rail — plus audience intelligence, cost optimization, and a brass-themed ops console.",
    link: "https://www.airsurfaceglobal.com",
    tags: ["Next.js", "GSAP", "Globe.gl", "AI", "Logistics"],
    gradient: "from-[#b8860b] to-[#8b6914]",
    preview: "/previews/airsurfaceglobal.png",
    sort_order: 15,
  },
  {
    id: "seed-proj-2",
    title: "North Falmouth Pharmacy",
    subtitle: "LTC Pharmacy · Cape Cod",
    number: "03",
    description:
      "Long-term care pharmacy website serving Cape Cod facilities — eMAR integration, compliance packaging, immunizations, enrollment forms.",
    link: "https://www.nfpltc.com",
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    gradient: "from-[#f59e0b] to-[#ea580c]",
    preview: "/previews/nfpltc.png",
    sort_order: 20,
  },
  {
    id: "seed-proj-3",
    title: "Auburn RX Pharmacy",
    subtitle: "Independent Retail Pharmacy",
    number: "04",
    description:
      "Modern pharmacy website featuring online refill requests, immunization booking, prescription transfer, and local healthcare resources.",
    link: "https://auburnrx.vercel.app",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
    gradient: "from-[#0ea5e9] to-[#0284c7]",
    preview: "/previews/auburnrx.png",
    sort_order: 30,
  },
  {
    id: "seed-proj-4",
    title: "Saint Francis Medical",
    subtitle: "Healthcare & Medical Practice",
    number: "05",
    description:
      "Patient-focused medical practice website with appointment booking, services overview, provider profiles, and HIPAA-conscious contact forms.",
    link: "https://saint-francis-medical.vercel.app",
    tags: ["Next.js", "React", "Tailwind CSS", "Vercel"],
    gradient: "from-[#8b5cf6] to-[#6d28d9]",
    preview: "/previews/saint-francis.png",
    sort_order: 40,
  },
  {
    id: "seed-proj-5",
    title: "EchoNest",
    subtitle: "AI Music Platform",
    number: "06",
    description:
      "A music streaming and discovery platform powered by AI. Features smart playlists, listening analytics, music recommendations, and MCP integration for agent-to-agent communication.",
    link: "https://echonest-app.vercel.app",
    tags: ["Next.js", "AI", "Music", "Streaming", "MCP"],
    gradient: "from-[#00868e] to-[#006b72]",
    preview: "/previews/echonest.png",
    sort_order: 50,
  },
];
